import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import Header from '@/components/Header'
import ConvexClerkProvider from "@/components/ConvexProviderWithClerk";

export const metadata: Metadata = {
  title: 'Clarity SEO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClerkProvider>
          <ConvexClerkProvider>
            <Header />
            {children}
          </ConvexClerkProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}